// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: notification/notification.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationGreeter_GetNotification_FullMethodName = "/notification.NotificationGreeter/GetNotification"
)

// NotificationGreeterClient is the client API for NotificationGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationGreeterClient interface {
	GetNotification(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotificationMessage], error)
}

type notificationGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationGreeterClient(cc grpc.ClientConnInterface) NotificationGreeterClient {
	return &notificationGreeterClient{cc}
}

func (c *notificationGreeterClient) GetNotification(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotificationMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NotificationGreeter_ServiceDesc.Streams[0], NotificationGreeter_GetNotification_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, NotificationMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NotificationGreeter_GetNotificationClient = grpc.ServerStreamingClient[NotificationMessage]

// NotificationGreeterServer is the server API for NotificationGreeter service.
// All implementations must embed UnimplementedNotificationGreeterServer
// for forward compatibility.
type NotificationGreeterServer interface {
	GetNotification(*Empty, grpc.ServerStreamingServer[NotificationMessage]) error
	mustEmbedUnimplementedNotificationGreeterServer()
}

// UnimplementedNotificationGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationGreeterServer struct{}

func (UnimplementedNotificationGreeterServer) GetNotification(*Empty, grpc.ServerStreamingServer[NotificationMessage]) error {
	return status.Errorf(codes.Unimplemented, "method GetNotification not implemented")
}
func (UnimplementedNotificationGreeterServer) mustEmbedUnimplementedNotificationGreeterServer() {}
func (UnimplementedNotificationGreeterServer) testEmbeddedByValue()                             {}

// UnsafeNotificationGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationGreeterServer will
// result in compilation errors.
type UnsafeNotificationGreeterServer interface {
	mustEmbedUnimplementedNotificationGreeterServer()
}

func RegisterNotificationGreeterServer(s grpc.ServiceRegistrar, srv NotificationGreeterServer) {
	// If the following call pancis, it indicates UnimplementedNotificationGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationGreeter_ServiceDesc, srv)
}

func _NotificationGreeter_GetNotification_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotificationGreeterServer).GetNotification(m, &grpc.GenericServerStream[Empty, NotificationMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NotificationGreeter_GetNotificationServer = grpc.ServerStreamingServer[NotificationMessage]

// NotificationGreeter_ServiceDesc is the grpc.ServiceDesc for NotificationGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationGreeter",
	HandlerType: (*NotificationGreeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNotification",
			Handler:       _NotificationGreeter_GetNotification_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "notification/notification.proto",
}
