// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: notification/notification.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationGreeterClient is the client API for NotificationGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationGreeterClient interface {
	GetNotification(ctx context.Context, in *Empty, opts ...grpc.CallOption) (NotificationGreeter_GetNotificationClient, error)
}

type notificationGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationGreeterClient(cc grpc.ClientConnInterface) NotificationGreeterClient {
	return &notificationGreeterClient{cc}
}

func (c *notificationGreeterClient) GetNotification(ctx context.Context, in *Empty, opts ...grpc.CallOption) (NotificationGreeter_GetNotificationClient, error) {
	stream, err := c.cc.NewStream(ctx, &NotificationGreeter_ServiceDesc.Streams[0], "/notification.NotificationGreeter/GetNotification", opts...)
	if err != nil {
		return nil, err
	}
	x := &notificationGreeterGetNotificationClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NotificationGreeter_GetNotificationClient interface {
	Recv() (*NotificationMessage, error)
	grpc.ClientStream
}

type notificationGreeterGetNotificationClient struct {
	grpc.ClientStream
}

func (x *notificationGreeterGetNotificationClient) Recv() (*NotificationMessage, error) {
	m := new(NotificationMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotificationGreeterServer is the server API for NotificationGreeter service.
// All implementations must embed UnimplementedNotificationGreeterServer
// for forward compatibility
type NotificationGreeterServer interface {
	GetNotification(*Empty, NotificationGreeter_GetNotificationServer) error
	mustEmbedUnimplementedNotificationGreeterServer()
}

// UnimplementedNotificationGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationGreeterServer struct {
}

func (UnimplementedNotificationGreeterServer) GetNotification(*Empty, NotificationGreeter_GetNotificationServer) error {
	return status.Errorf(codes.Unimplemented, "method GetNotification not implemented")
}
func (UnimplementedNotificationGreeterServer) mustEmbedUnimplementedNotificationGreeterServer() {}

// UnsafeNotificationGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationGreeterServer will
// result in compilation errors.
type UnsafeNotificationGreeterServer interface {
	mustEmbedUnimplementedNotificationGreeterServer()
}

func RegisterNotificationGreeterServer(s grpc.ServiceRegistrar, srv NotificationGreeterServer) {
	s.RegisterService(&NotificationGreeter_ServiceDesc, srv)
}

func _NotificationGreeter_GetNotification_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotificationGreeterServer).GetNotification(m, &notificationGreeterGetNotificationServer{stream})
}

type NotificationGreeter_GetNotificationServer interface {
	Send(*NotificationMessage) error
	grpc.ServerStream
}

type notificationGreeterGetNotificationServer struct {
	grpc.ServerStream
}

func (x *notificationGreeterGetNotificationServer) Send(m *NotificationMessage) error {
	return x.ServerStream.SendMsg(m)
}

// NotificationGreeter_ServiceDesc is the grpc.ServiceDesc for NotificationGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationGreeter",
	HandlerType: (*NotificationGreeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNotification",
			Handler:       _NotificationGreeter_GetNotification_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "notification/notification.proto",
}
