// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: users/users.proto

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsersGreetClient is the client API for UsersGreet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersGreetClient interface {
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
}

type usersGreetClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersGreetClient(cc grpc.ClientConnInterface) UsersGreetClient {
	return &usersGreetClient{cc}
}

func (c *usersGreetClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/users.UsersGreet/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersGreetServer is the server API for UsersGreet service.
// All implementations must embed UnimplementedUsersGreetServer
// for forward compatibility
type UsersGreetServer interface {
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	mustEmbedUnimplementedUsersGreetServer()
}

// UnimplementedUsersGreetServer must be embedded to have forward compatible implementations.
type UnimplementedUsersGreetServer struct {
}

func (UnimplementedUsersGreetServer) GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedUsersGreetServer) mustEmbedUnimplementedUsersGreetServer() {}

// UnsafeUsersGreetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersGreetServer will
// result in compilation errors.
type UnsafeUsersGreetServer interface {
	mustEmbedUnimplementedUsersGreetServer()
}

func RegisterUsersGreetServer(s grpc.ServiceRegistrar, srv UsersGreetServer) {
	s.RegisterService(&UsersGreet_ServiceDesc, srv)
}

func _UsersGreet_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersGreetServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UsersGreet/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersGreetServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersGreet_ServiceDesc is the grpc.ServiceDesc for UsersGreet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersGreet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UsersGreet",
	HandlerType: (*UsersGreetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _UsersGreet_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/users.proto",
}
